### ISSUE TITLE
CTRL + click on tabs doesn't show context menu

### ISSUE THREAD

**Issue by koenpunt** [textmate/bugs#11]
When holding <kbd>CTRL</kbd> and clicking on a tab, the context menu does not appear like it does when right-clicking.

**Comment by dusek** [comment]
Hopefully a related observation - attachments in Mail.app behave the same way (I think it wasn't like that always and started recently, i.e. in Yosemite, but am not 100% sure).

**Comment by koenpunt** [comment]
Also, middle-clicking a tab to close it would be a nice addition.

**Comment by dusek** [comment]
I think you should file a feature request in textmate/requests for the middle click suggestion, it's a separate issue.

**Comment by koenpunt** [comment]
Yeah I know, but as it is probably related to the same part in the codebase.. (https://github.com/textmate/requests/issues/3)

**Comment by dusek** [comment]
@koenpunt btw. which OS X version are you running? Yosemite?

**Comment by koenpunt** [comment]
Yep, Yosemite 10.10.3 (14D98g) (the beta)

**Comment by sorbits** [comment]
It appears that the system will not automatically handle control-click 
when the view in question has sub-views: 
http://stackoverflow.com/questions/7128774/controlclick-not-triggering-menuforevent

To me this seems like an OS bug, the workaround would be to subclass the 
controls used in tabs and override the menuForEvent: method to do the 
proper thing — I can add it to the core tab item view and the roll 
over button used for the overflow and close buttons, that leaves only 
the add tab button, I don’t think there is enough justification for 
adding a subclass for this button.
