### ISSUE TITLE
TextMate will exit fullscreen on pressing [esc] when the file browser has focus

### ISSUE THREAD

**Issue by koenpunt** [textmate/bugs#18]
When TextMate is running fullscreen and I have a file selected in the file browser, pressing <kbd>ESC</kbd> will exit fullscreen.

Found out about this when I wanted to dismiss renaming a file and pressed <kbd>ESC</kbd> twice.

**Comment by sorbits** [comment]
This is default system behavior: When nothing else uses escape, it exits 
fullscreen mode.

I occasionally use this in other apps (when accidentally triggering 
fullscreen), so I don’t think TextMate should overload key handling to 
disable this feature.

**Comment by koenpunt** [comment]
Oh well, didn't know that. Still undesired IMO, but I'll see if I can disable it in OS X itself than.
