### ISSUE TITLE
Jump to next / previous mark shortcut collides with standard 'switch to next / previous window' shortcut from apple

### ISSUE THREAD

**Issue by dwt** [textmate/bugs#19]
Not sure if this is also in the english version of the os, but it definitely is in the german and is quite annoying for text mate to override with a different meaning.

Therefore I request this shortcut to change - at least on versions of os x where it already has a different meaning.

**Comment by sorbits** [comment]
This issue is being discussed here https://github.com/textmate/textmate/pull/1316
