### ISSUE TITLE
Failure running “Toggle ERb Tags”.

### ISSUE THREAD

**Issue by MCodyB** [textmate/bugs#2]
Error: Toggle ERb Tags:20: undefined method `[]' for nil:NilClass (NoMethodError)

Steps to reproduce:
1. Open a HTML(Ruby - ERB) doc.
2. On a line other than the first (see later)
3. type something
4. select it with mouse or `shift+arrows`
5. Press `ctrl shift >` to toggle `<%= something %>`
6. press `ctrl shift >` second time (i.e. to get from `<%= something %>`  to `<% something %>`
7. Error will raise.

And if you're on line 1 of the document
1. Follow above steps 1-6
2. `x` will turn into `<%= ${0}x %>`. But instead of an error it then will continue to toggle normally, except for the added `${0}`

Output from a few attempts on the first line

```
<%= ${0}s %> <%- ${0}s -%> normal text <%# ${0}x %>
```

EDIT: Sorry, TextMate version 2.0-alpha.9547, OS 10.9.2

**Comment by sorbits** [comment]
Please use the relevant bundle’s issue tracker.
