### ISSUE TITLE
After v2.0-beta.10 "Go To Related File" doesn't work anymore

### ISSUE THREAD

**Issue by koenpunt** [textmate/bugs#21]
Reproducing this is easy, download the latest version, beta 11.4, and run. Open a file which has a related file, `Navigate > Go to Related File`, nothing happens. Now download beta 10, open file, `Navigate > Go to Related File`, goes to related file.

So for now I've reverted to beta 10.

Had some issues with textmate not remembering file type settings, but it seems that has been fixed in the meantime

**Comment by sorbits** [comment]
Works fine for me on latest beta.

Please provide some more info, does the menu item work? What sort of 
file names are you switching between? Do you have custom values for the 
relatedFilePath, exclude, or binary settings keys (you can press ⌃R on 
a line containing "$TM_QUERY" to dump your settings)? Did you try on a 
new user account? Did you try 
https://github.com/textmate/textmate/wiki/Reverting-To-Defaults etc.

For future reference, I think it makes more sense to send these reports 
to the mailing list.

As for not remembering file type settings, that is also not something I 
am aware of was ever broken.

**Comment by koenpunt** [comment]
You want to me to move this to the mailing list? I can do that. And yes I have custom values for `relatedFilePath`, but not really fancy stuff:

``` ini
# "Go to Related File" action for Rspec test files
[ *.rb ]
relatedFilePath = "${TM_FILEPATH/\/app\/(.+)/\/spec\/${1/(?=\.rb$)/_spec/}/}"

[ *_spec.rb ]
relatedFilePath = "${TM_FILEPATH/\/spec\/(.+)/\/app\/${1/_spec(?=\.rb$)//}/}"

[ *.html.erb ]
relatedFilePath = "${TM_FILEPATH/\/app\/(.+)/\/spec\/${1}_spec.rb/}"

[ *.erb_spec.rb]
relatedFilePath = "${TM_FILEPATH/\/spec\/(.+)_spec.rb/\/app\/${1}/}"
```

**Comment by sorbits** [comment]
Please create a project with some sample files, your customized 
.tm_properties, and steps to reproduce for this project.

**Comment by koenpunt** [comment]
[textmate-related-file.zip](https://github.com/textmate/bugs/files/349542/textmate-related-file.zip)

When you open the project with beta 10, and open the `test.rb` file, `Go to Related File` will take you to `test_spec.rb` and from there `Go to Related File` will take you back to `test.rb`. 
In any version after that, eg the latest beta, 11.4, this doesn't work.

Has something changed with the format of `relatedFilePath`?

**Comment by koenpunt** [comment]
And when you press <kbd>⌃</kbd><kbd>R</kbd> on the `$TM_QUERY` line, you'll see that `relatedFilePath` is set to the correct path, but it doesn't switch to it.

**Comment by nuritnt** [comment]
why was this closed? or what was the solution? 
Have the same problem with v2.0-rc.4..

**Comment by sorbits** [comment]
The issue was closed via a commit that fixed the problem.

Please provide additional details if you have a similar problem, but 
best to use one of the support channels, see 
http://macromates.com/support
