### ISSUE TITLE
Tooltip is displayed on different screen

### ISSUE THREAD

**Issue by dwt** [textmate/bugs#24]
When I was viewing a tooltip (from a hg-annotation in the html output window), at first it looked as if the tooltip wasn't showing up at all.

After some time, I noticed that the tooltip did show up - but on an entirely different monitor.

IMO this should not happen and is a bug that needs addressing. See attached screenshots for an example of this.

![bildschirmfoto 2016-11-23 um 15 40 41 2](https://cloud.githubusercontent.com/assets/57199/20568886/402f7b78-b19e-11e6-9a99-04d44b85686d.png)
<img width="1280" alt="bildschirmfoto 2016-11-23 um 15 40 41" src="https://cloud.githubusercontent.com/assets/57199/20568887/405aaae6-b19e-11e6-845b-c87d7f5c4e3d.png">

Some context: the active annotation window is on the lower screenshot, in it, I mouse over a line, which triggers the tooltip displayed on the upper screenshot. The code and some irrelevant context is removed for privacy reasons.

**Comment by sorbits** [comment]
Please reformulate using “Steps to Reproduce” and include OS 
version.

See https://github.com/textmate/textmate/wiki/Writing-Bug-Reports

**Comment by sorbits** [comment]
If you are talking about tool tips from the HTML output window (which is what seems to be visible on your screenshot) then these are handled by the system and not something TextMate controls.
