### ISSUE TITLE
Cursor huge

### ISSUE THREAD

**Issue by Kamik423** [textmate/bugs#26]
the first time I launched TextMate since the latest update my cursor looks like this, while TextMate is selected and the cursor hovers over it:

<img width="977" alt="untitled" src="https://user-images.githubusercontent.com/16278233/38560019-e7f94bc8-3cd4-11e8-9f78-fcda7fcd45ad.png">

**Comment by infininight** [comment]
This is the fourth report we've had about this but so far we've been unable to reproduce this locally. It seems to not be widespread but whatever the trigger for it is seems to be persistent for those affected.

So far there doesn't seem to be a pattern as it can happen with the current nightly build back to at least RC4. It does seem to be a recent thing though so it could be tied to an OS version. What macOS build are you on?

There is a workaround: This is a custom cursor for dark themes to improve legibility, switching to a light theme corrects the issue.

**Comment by Kamik423** [comment]
I am currently on `10.13.5 Beta (17F35e) - MacBook Pro (15-inch, 2016)`
I just deleted the solarized theme while still having it selected and turned TextMate off and on again. Then window is now white (Black Line number bar), but the cursor is still huge.
A thing I've noticed: It is installed via brew, and when I tried to updated it had a problem with not being able to overwrite the `mate` shell extension. So I manually deleted that file. After updating the extension did not work (I did not launch TextMate however), so I force reinstalled it with brew. Maybe the problem occurred somewhere in that process.

**Comment by infininight** [comment]
You can change the theme from View → Theme, no need to delete anything. Odd that Homebrew is touching the `mate` executable, should really just be managed by TextMate. But it wouldn't be involved, nothing in `mate` affects the core application.

_For our reference: The first user was using 10.13.5 beta 1, but reported that it started happening during the 10.13.4 beta period. The other two users did not reply back to version requests._

**Comment by infininight** [comment]
OK we've gotten a report that this has been corrected in 17F45c of 10.13.5, once you upgrade can you confirm this?

**Comment by Kamik423** [comment]
Can confirm

**Comment by infininight** [comment]
Great, thanks for the confirmation and report!
