### ISSUE TITLE
Find (cmd-f) dialog does not stay in it's desktop "space" when switching desktops.

### ISSUE THREAD

**Issue by jeffreydwalter** [textmate/bugs#29]
![image](https://user-images.githubusercontent.com/567047/45870339-42c46280-bd50-11e8-8988-a92632dcd8de.png)
![image](https://user-images.githubusercontent.com/567047/45870587-d9911f00-bd50-11e8-9c97-9c7277331ea6.png)

Steps to reproduce:
1. Have one or more documents open in TextMate.
2. Have them all on a single Desktop.
```
All of my TextMate documents are open in a single Desktop:
```
![image](https://user-images.githubusercontent.com/567047/45870649-ffb6bf00-bd50-11e8-80e4-0a2fc9439d00.png)
3. Open the `Find` dialog by pressing cmd-f.
![image](https://user-images.githubusercontent.com/567047/45870707-24129b80-bd51-11e8-81cf-618ac8e2deb7.png)
4. Switch to some other application on another Desktop (cmd-tab).
![image](https://user-images.githubusercontent.com/567047/45870763-53c1a380-bd51-11e8-8f2d-e34a27d1de62.png)
5. You may have to cmd-tab to bring TextMate back into focus (which will present you with the `Find` dialog on the Desktop you just switched to, instead of taking you back to the one with all of the TextMate documents.

Expected Result: The `Find` dialog will not appear in a Desktop that doesn't have any TextMate documents open in it.

Actual Result: The `Find` dialog "follows" you to the other Desktop, even if it doesn't have any TextMate documents open in it.

**Comment by sorbits** [comment]
Sorry, but we no longer support TextMate 1.x.

I would strongly encourage you to upgrade to version 2: https://macromates.com/download

**Comment by jeffreydwalter** [comment]
Didn't realize 1.x was old news! Looks like 2 behaves better. Thanks!
