### ISSUE TITLE
Zoom Cursor Tracking

### ISSUE THREAD

**Issue by infininight** [textmate/bugs#3]
The Zoom accessibility feature in OS X allow text cursor tracking (so that when you are typing you don’t have to move the mouse to move the zoom window to where you’re currently typing text)
1. Enable Zoom in System Preferences -> Accessibility -> Zoom, and ensure you have checked the box for “Zoom follows text cursor”.
2. Load TextEdit (this is for comparison reasons, showing the expected result)
   Zoom in with either Opt+Cmd + to a point where you’re seeing only a portion of a TextEdit document. 
   Type something, enough for it to go off the view, Zoom will “jump” to the current place where the text cursor is, and keeps doing so as you go onto a new line, etc.
3. Open up a TextMate document, any code, any theme. I mainly use HTML, CSS, JS, Python, PHP and SQL.
   
   Create a simple script, making sure you make it longer than the zoomed in view, you’ll find that Zoom only follows part of what the text cursor does, Normally only a new line jump. 
4. Remember to go back into Accessibility in System Preferences and disable Zoom follows text cursor - otherwise you’ll have your screen jumping around and this can be disorientating for a non-Zoom user. 

Opt-Cmd + (Zoom In)
Opt-Cmd - (Zoom out)
Ctrl + two finger drag up/down (dynamic zoom with trackpad)
Opt-Cmd 8 (enable/disable zoom)

_Originally reported via email_

**Comment by dusek** [comment]
Thanks very much for the report, I'll take a look at it this or the next weekend.

**Comment by dusek** [comment]
I looked at this and it looks like two separate issues:
- #4 Zoom does not follow cursor correctly at beginning of line
- #5 Zoom does not follow cursor horizontally while typing

The second one is of course more important for the user (and more mysterious for me :-)

**Comment by dusek** [comment]
FYI, both dependent issues (#3 and #4) have been resolved in latest master of textmate/textmate.

**Comment by dusek** [comment]
@infininight I was wondering if you got any feedback from the client about whether the issue has been resolved in latest releases and whether this issue can thus be closed?

**Comment by infininight** [comment]
Got a reply back today, he says it works great!

**Comment by dusek** [comment]
That's great to hear!
