### ISSUE TITLE
New - File Browser (thumbsdown)

### ISSUE THREAD

**Issue by panreach** [textmate/bugs#31]
Latest update (TextMate version 2.0-rc.14) for opening a file browser... is NOT my favorite.

HaRdCoRe TextMate 1/2 fan heRe using this software for years...

Unfortunately, I won't be able to upgrade to mojave with my 17" laptop (last build).  The mojave changes to the file browser went amok.  The grey background is not that bad.  But, when I use Fuse to connect to remote servers, it's just a totally different experience.  (Functionality wise- it still works..)

But, I hope there's a good reason for this change...

... end rant

Cheers on the beautiful software (w/#SweetCursors)!

-panreach

**Comment by sorbits** [comment]
If you are talking about 
https://github.com/textmate/textmate/commit/80681fc6a4e42adeb95790d2b28c8daeecb1d937 
then that was added in rc.15 (which only 10.14 users should see as an 
update, when on nightly builds, and which is work in progress).

If you are talking about something else, please be more specific.

tag: closed
