### ISSUE TITLE
Large file does not properly paint text when scrolling.

### ISSUE THREAD

**Issue by gkellogg** [textmate/bugs#33]
After upgrading to MacOS 10.15 (Catalina), scrolling through a large file (>6000 lines) often does not properly paint the text. This can be temporarily corrected by dragging a selection over the missing text.

* OS version:  MacOS 10.15 (Catalina)
* Textmate version: 2019-09-15 (v2.0)
* Affected file: https://github.com/w3c/json-ld-api/blob/master/index.html.
* File language: HTML

Most recently, I noticed this when moving to line 3500 in the referenced file and scrolling downwards.

<img width="1295" alt="Screen Shot 2019-10-09 at 10 22 41 AM" src="https://user-images.githubusercontent.com/46296/66504777-c39aed00-ea7e-11e9-996f-261ecbee4a76.png">

**Comment by bastilian** [comment]
Have you tried updating to **2.0.3** and see if the issue occurs there as well?

I've tried reproducing this on Catalina, but it renders correctly and scrolls smoothly with TextMate v 2.0.3.

**Comment by sorbits** [comment]
My reply regarding this sent to the mailing list: https://lists.macromates.com/textmate/2019-December/041292.html

In summary, at least two other applications seems to show similar behavior on macOS 10.15 and the lack of refresh spanning two different NSView’s, plus what is redrawn is exactly 640 pixels wide in the above screenshot, makes it look like a bug in the window/view compositor/tiler introduced on macOS 10.15.

**Comment by bastilian** [comment]
After not seeing it before, I have been starting to experience it as well (on 10.15.4 (19E287)).

I did try `defaults write com.macromates.TextMate enableResponsiveScroll -bool YES`, but with no difference.

Is there anything that can be done to help investigate how to possibly avoid and address this?

**Comment by bastilian** [comment]
Here are a few more examples of the issue:

It's not only 640px wide sections, but full width parts of the text view:

![Screenshot 2020-05-23 at 14 17 04](https://user-images.githubusercontent.com/7757/82730481-63507700-9d00-11ea-9812-e3929492b9a4.png)

It also happens that only parts of the gutter aren't rendered properly, it does sometimes still render parts above or below an area that does not render:

![Screenshot 2020-05-23 at 14 16 55](https://user-images.githubusercontent.com/7757/82730523-b62a2e80-9d00-11ea-9559-221e4b88948d.png)

I tried to see if there is anything that can be set on the views to force it to render the whole view somehow, but my Cocoa/Objective-C skills are very limited.

**Comment by sorbits** [comment]
I have only experienced this once myself, but based on what I experienced, it is very clear that this is an OS bug and nothing to do with TextMate.

That said, a future version will make changes to how it deals with drawing (going full in on layers), so if Apple doesn’t fix it, possibly that change will, but it is a major upgrade, so no ETA.

**Comment by bastilian** [comment]
It looks like Apple fixed the issue in macOS 11 Big Sur!

I've been using TextMate on the Beta since the first build and there have not been any issues like this, with files that usually exhibited these issues.

**Comment by gkellogg** [comment]
As I'm the creator, I'm going to close, as the issue seems to be resolved.
