### ISSUE TITLE
TextMate crashes when accessibility features are activated

### ISSUE THREAD

**Issue by DerBunteBall** [textmate/bugs#34]
Hey all,

I have an iMac running macOS Catalina 10.15.2. I upgraded from 10.14.6 Mojave.

Since these upgrade TextMate crashes all the time when accessibility features like Zoom or VoiceOver are activated.

### Issue

TextMate crash completely after starting. From time to time the main windows appears but a click on it is enough to bring it to crash.

I think it's a problem in the GUI component. Also experienced things like this with other programs in the past. Often the GUI (Library) and the accessiblity software (here as part of macOS) don't love the other part.

### Wanted

It should run again normally 😢 Aspecially because TextMate is the only modern editor where the zoom focus following mechanism works because it's really native macOS software.

### Reproduction

Simply active the zoom in system settings. Then you TextMate will explode. If it's already running it dies. If it is not running it dies a second after starting. Eventually it doesn't appear.

### Environment

it's a macOS 10.15.2 Catalina on an iMac (I think mid 15). TextMate installed with Homebrew. Accessibility features are activated aspecially the Zoom (also with color inversion) and VoiceOver when needed.

### Crash Report

TextMate already sent a ton of reports while my tests I think.

This is one of the newest: https://api.textmate.org/crashes/425625

If more info is needed please tell me.

Best Regards

PS. Sorry for my horrible bad english.

**Comment by sorbits** [comment]
Please retest with latest test build.

You can update to latest test build by holding down option (⌥) when opening the TextMate menu and then select “Check for Test Build”. Alternatively hold down option when clicking “Check Now” in Preferences → Software Update.

**Comment by DerBunteBall** [comment]
Couldn't upgrade via TextMate (due to the crash in 2.0.3 - it's really unsuable).

Took 2.0.4 from GitHub. First start looks great. I have the normal window again and can type stuff and so on while zoom is activated.

What was the reason for the crash?

Best Regards

**Comment by sorbits** [comment]
> What was the reason for the crash?

I added range checks to the API involved in obtaining text ranges for the accessibility functions, as that’s where the crash happened.

It does indicate misuse of this API, so I will have to dig a little deeper for a satisfying explanation, but at least now misuse of the API should not result in a crash.
