### ISSUE TITLE
Text Selection Background(Bg) Color is Almost Same As Dark-Bg In Sunburst (Dark)Theme. "Find" Removes Selection Bg Color

### ISSUE THREAD

**Issue by atErik** [textmate/bugs#36]
Hi, to get DARK mode, i use "Sunburst" Theme, & it can provide dark/black background for documents/files.

When text/code is selected, then selection's background color is almost same as dark background !
selection area has dark-gray or very-dark-gray background color !
so selection/selected area is not distinguished, and hard to understand which part is actually selected.

And when i press Command+F then "Find" window appears, (program focus moves away from opened file window into the "Find" window), and then selected text area's background (very-dark-gray) color goes away, & becomes completely dark, same as background !! at that point, no way to understand which part is/was selected & which part is not selected.
So it is very hard to work when doing text Find+Replace works.
As its not shown which exact part is selected & going to be replaced,
etc, etc.

Please fix those BUG/issues.

In dark theme mode, selected area's background-color needs to be some OTHER-COLOR which is NOT-DARK & NOT-GRAY & not a very-darker-shade of other color.
i would suggest to use: some shade of blue. ( in macOS Terminal dark mode, selected text color is white & background color is light-blue ).

And when "Find" window appears, then the selection should remain selected with same background color even when the focus is not that document.

**Comment by bastilian** [comment]
Hej @atErik,

This is not necessarily a bug. Themes are just sets of colour preferences that don't necessarily follow accessibility recommendations.

But it is possible to adjust the colours of any theme to better suit your preferences.

You can do so, by opening the "Bundle Editor" under the "Bundles" menu. In the Bundle Editor look for "Themes" in the leftmost column. In the second column choose "Themes" again, which will give you a list of themes including "Sunburst".

It should look like this: 
![Screenshot 2020-08-02 at 09 13 22](https://user-images.githubusercontent.com/7757/89117862-622a8b80-d4a1-11ea-8371-b1677c8492b2.png)

The lines 7 & 8 are what you'll be interested in. They set the colours for the selection and the lineHighlight.

You can also use this handy theme editor to create your very own theme: https://github.com/aziz/tmTheme-Editor

**Comment by atErik** [comment]
THANK YOU, @bastilian.

after i made some changes, when i have used TextMate > File > "Save" option, then it shows error!
![Screen Shot 2020-09-06 at 9 03 35 PM](https://user-images.githubusercontent.com/9985911/92347480-101eec00-f085-11ea-87aa-d7a9e185e736.png)
( i'm not sure why this error was shown, but i'm guessing error occurred due to lack of privileged write access on theme config file)

where exactly files are, may be i should manually open & edit them ?

Also Thanks, for the link to tmTheme-Editor, i will play with it, it would be great to have my own choice of colors, etc.

<b>EDIT:</b>

i was keeping backup of old data as "comment" by using `'#'` symbol, but that is wrong character(s) to create/keep comment/note,  
that is why above shown error was occurring.  
once i have changed the `'#'` symbol into `/* comment/note */` then "Save" operation succeeded (without any further error).

<b>bg</b> = background

in Bundle editor, changed the "Sunburst" theme  
&#160;&#160;`lineHighlight = '#FFFFFF1A';`  
into  
&#160;&#160;`lineHighlight = '#FFFFFF0F';`  
and changed  
&#160;&#160;`selection = '#DD...';`
into  
&#160;&#160;`selection = '#253B76';`  
& in TextMate main-menu > File > "Save" (Save theme) worked.

Color codes : reference: https://www.w3schools.com/colors/colors_shades.asp  
when color code is 6-digits hexadecimal then its `#hhhhhh` = `#RRGGBB`  
( where h = hexa-decimal numbers , R = red , G = greeen , B = Blue )  
when color code is 8-digits hexadecimal then its `#hhhhhhhh` = `#RRGGBBAA`  
( where A = alpha-channel (how much transparent or opaque the 6-digit color will be) code, 00 makes it fully transparent, & FF makes it fully opaque )

re-selected the theme "Sunburst" again, then new changes are reloaded & re-applied by TextMate.

TextMate was able to show light-blue background color for selected text.
and it remains also (another lighter shade of) light-blue, when focus moves to "Find"/other window.
SO YOUR SUGGESTED HINTS WORKED.

by the way, there is another textmate theme "Blackboard" &lt;-- this one can show light-blue colored highlight background (similar to macOS when DARK mode is enabled) for selected text, and can also keep the selection visible/distinguished clearly, even when the focus is moved on to the small "Find"-window in TextMate, but this theme's background-color is gray, so its not-very-dark which i prefer.

when i went back to edit "Sunburst" again, my `/* comments */` were auto removed !!  
How to add comment/note inside theme config ?

i have tried again, this time edited the "Blackboard" theme,  
changed  
&#160;&#160;`background = '#0C1021';`  
into  
&#160;&#160;`background = '#000000';`  
& "Save" worked w/o error.

re-selected the "Blackboard" theme again in a working document in TextMate.  
now background/bg color changed from "gray" into "very-dark"(black) mode.  
and in this theme, highlighted/selected text can also remain selected with light-blue color, even when focus moves onto "Find"/other window.

actually, when "Blackboard" theme was selected inside bundle-editor, then i got the idea to use/copy color codes from it, to apply into "Sunburst".

here is a view of text selection, (when "Find"-window is not focused, or not in top, or not in front).  
![Screen Shot 2020-09-08 at 12 55 19 AM](https://user-images.githubusercontent.com/9985911/92448819-06bd7e80-f16e-11ea-95cf-afdfb2b2e100.png)

now in "Sunburst" theme,  
![Screen Shot 2020-09-08 at 6 22 21 PM](https://user-images.githubusercontent.com/9985911/92543525-93188180-f200-11ea-8391-21700a22ba59.png)
as you can see when "Find" window appears, found item now is shown with blue bg color at-least, & can be distinguished (which part is going to be affected) than rest of the code line(s), BUT it is still has very very light blue bg color, though its better than before, i just have to make it little more brighter blue, then my objective is done for this theme.

<b>EDIT:</b>  
changed above color code lines into:  
&#160;&#160;`selection = '#253B76FF';`  
&#160;&#160;`lineHighlight = '#FFFFFFFF';`  
but result is still same, bg color still remains very-very-light blue. Brightness of bg blue did not increase.

<b>EDIT:</b>  
again edited color code into:  
&#160;&#160;`selection = '#2850E0FF';`  
&#160;&#160;`lineHighlight = '#FFFFFFFF';`  
now it appears to be better than before . ( now i can work in this environment ).
![Screen Shot 2020-09-08 at 7 09 57 PM](https://user-images.githubusercontent.com/9985911/92546232-eee60900-f206-11ea-8dcf-b71529c9be17.png)
