### ISSUE TITLE
TextMate won't save to FAT32 thumbdrives.

### ISSUE THREAD

**Issue by Stokestack** [textmate/bugs#39]
This has been going on for years, on numerous flash drives. You can create a file in TextMate and save it, but after that you can never modify it. You get:

Failed replacing appPW.txt with /Volumes/THUMBDRIVE/.TemporaryItems/folders.501/TemporaryItems/NSIRD_TextMate_IP31J8/appPW.txt: The file “appPW.txt” couldn’t be saved in the folder “whatever”.

Other applications can open and save the file just fine. This is such a pervasive and longstanding problem that I must now abandon TextMate for good. I'm happy to provide further info, however.

Latest occurrence was under Mac OS 11.6.4, TextMate 2.0.23

**Comment by sorbits** [comment]
Try add this to `~/.tm_properties `

    atomicSave = never

**Comment by Stokestack** [comment]
Thanks for your reply. I realize that this is pretty simple, but I'm just not willing to mess with it on every system I have and then have to remember to do it all the time in the future. I'm just going to use Atom or something else.

If this setting causes such problems, it should be off by default.

**Comment by Stokestack** [comment]
Closed on what basis?
