### ISSUE TITLE
Comments are wrapped regardless of soft wrapping setting

### ISSUE THREAD

**Issue by cycomachead** [textmate/bugs#6]
![screen shot 2014-07-24 at 2 07 12 pm](https://cloud.githubusercontent.com/assets/1505907/3694885/57d46d78-1377-11e4-8251-0406a0f6351c.png)

**Comment by sorbits** [comment]
See 
https://github.com/textmate/textmate/wiki/FAQ#how-to-disable-soft-wrap

**Comment by cycomachead** [comment]
Sorry about that; thanks! :)
